// src/components/Error/errorModal.tsx
import { For, Show } from 'solid-js';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogTitle,
} from '~/components/ui/dialog';
import { globalStore } from '~/utils/globalStore';

const ErrorModal = () => {
  const err = globalStore.errorDetailsModal;

  return (
    <Dialog open={!!err}>
      <Show when={err}>
        {(err) => (
          <DialogContent>
            <DialogTitle>{err().title}</DialogTitle>
            <DialogDescription>{err().info}</DialogDescription>

            <Show when={err().rawError}>
              <div>{err().rawError}</div>
            </Show>

            <Show when={err().subErrors}>
              {(subErrors) => (
                <For each={subErrors()}>
                  {(se) => {
                    return (
                      <>
                        <div class="bold ">{se.title}</div>
                        <div class="bold">{se.rawError}</div>
                      </>
                    );
                  }}
                </For>
              )}
            </Show>
          </DialogContent>
        )}
      </Show>
    </Dialog>
  );
};

export default ErrorModal;

// components/Error/ErrorModal.vue
<template>
  <Dialog :open="err ? true : false" @update:open="() => (store.errorModal = null)">
    <DialogContent>
      <DialogTitle>
        {{ err?.title }}
      </DialogTitle>
      <DialogDescription>
        {{ err?.info }}
      </DialogDescription>
      <DialogDescription>
        <div v-if="err?.rawError">
          {{ err?.rawError }}
        </div>
        <div v-if="err?.subErrors && err.subErrors.length">
          <div v-for="se in err.subErrors">
            <div v-if="se.title" class="bold">
              {{ se.title }}
            </div>
            <div v-if="se.rawError" class="bold">
              {{ se.rawError }}
            </div>
          </div>
        </div>
      </DialogDescription>
    </DialogContent>
  </Dialog>
</template>

<script setup lang="ts">
import { useMainStore } from '~/composables/stores/useMainStore';

const store = useMainStore();

const err = computed(() => store.errorModal);
</script>
